config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :admins
  root 'tests#index'
  resources :configs
  resources :sliders
  resources :clas
  resources :contents
  resources :wenhuas
  resources :products
  resources :contacts
  resources :news
  resources :messages
  resources :logins
  resources :sitemaps
  resources :mains

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/cla.rb
class Cla < ActiveRecord::Base
  has_many :contents
end

app/models/config.rb
class Config < ActiveRecord::Base
  has_attached_file :logo, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :logo
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :cla
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
  has_many_kindeditor_assets :attachments, :dependent => :destroy
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :cla
  has_many :contents
end

app/models/main.rb
class Main < ActiveRecord::Base
  has_attached_file :mainimage, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :mainimage
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @contents = Content.all.order("updated_at DESC").paginate :page => params[:page], per_page:15

    @clas = Cla.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @content = Content.new
    @clas = Cla.all
  end

  # GET /tests/1/edit
  def edit
    @clas = Cla.all
  end

  # POST /tests
  # POST /tests.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to edit_content_path(@content), notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_path, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_path, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:cla_id, :title,:content,:auther,:image, :price,:summary, :icon, :name, :mail, )
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/wenhuas_helper.rb
module WenhuasHelper
end

app/views/contents/_form.html.erb
<script>


    $(document).ready(function () {


        $("#cla_select").click(function(){

        $('#cla_id').val($('#cla_select').val());

        });



        if($('#cla_id').val()>1)
        {
            $('#cla_select').val($('#cla_id').val());
        }else
        {
            $('#cla_id').val('1');
        }


    });






</script>

<div id="main">
  <div class="breadcrumb-wrapper">
    <div class="container">

      <div class="row">
        <div class="col-lg-12 col-md-12">
          <h3 class="title">关于我们</h3>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 ">
              <%= form_for(@content,:html => {:multipart => true}) do |f| %>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                      栏目:

                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.hidden_field :cla_id,class:"form-control",id:"cla_id"  %>
                    <select class="form-control" id="cla_select" style="width: 800px;" >
                      <% @clas.each do |cla| %>
                          <option value=<%= cla.id %> ><%= cla.title %></option>
                      <% end %>
                    </select>
                  </div>
                  <br>




                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                      标题

                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_field :title ,class:"form-control",style:'width:800px;' %>
                  </div>
                  <br>
                  <br>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                      作者

                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_field :auther, class:"form-control",style:'width:800px;' %>
                  </div>
                  <br>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                      图标

                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_field :icon, class:"form-control",style:'width:800px;' %>
                  </div>
                  <br>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                      产品价格

                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_field :price, class:"form-control",style:'width:800px;' %>
                  </div>
                  <br>



                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                      产品介绍

                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_area :summary,cols:"5", class:"form-control",style:'width:800px;' %>
                  </div>
                  <br>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                      产品图片

                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.file_field :image, class:"form-control",style:'width:800px;' %>
                  </div>

                  <br>
                  <% if @content.image_content_type.to_s.length>0 %>
                      <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                        <p class="pull-right">

                        </p>
                      </div>
                      <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">

                        <img src=<%=@content.image.url %> >

                      </div>
                  <% end %>
                  <br>
                  <br>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">

                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">

                  </div>
                  <br>




<% if params[:id] %>
                  <div >

                        <%= f.kindeditor :content, :simple_mode => true,:owner_id => @content.id,height:800 %>


                  </div>
                      <% end %>





                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">
                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <div class="pull-right">
                      <%= f.submit '确定',class:'btn btn-primary wpcf7-submit' %>
                    </div>

                  </div>




                  </div>
                  </div>
                  </div>
                  </div>
                  <!-- End 5th Row-->






              <% end %>

              </div>
  </div>
</div>

app/views/contents/edit.html.erb
<%= render 'admintop' %>
<%= render 'form' %>

app/views/contents/index.html.erb
<%= render 'admintop' %>
<div id="main">
  <div class="breadcrumb-wrapper">
    <div class="container">

      <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 row ">
        <h3 class="title">文章管理</h3>
        <table class="table table-striped table-bordered">
          <thead>
          <tr>
            <th>标题</th>
            <th>分类</th>
            <th>创建时间</th>
            <th>作者</th>
            <th>操作</th>
          </tr>
          </thead>
          <tbody>
          <%@contents.each do |content| %>
              <tr>
                <td><%= content.title %></td>
                <td>
                  <% @clas.each do |cla| %>

                      <% if content.cla_id.to_s == cla.id.to_s %>
                          <%= cla.title %>
                          <% break %>
                      <% end %>

                  <% end %>
                </td>
                <td><%= content.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                <td><%= content.auther %></td>
                <td><%= link_to '',edit_content_path(content),class:"icon-pencil",'data-no-turbolink' => true %>&nbsp;<%= link_to '', content, method: :delete, data: { confirm: 'Are you sure?' },class:"icon-trash" %></td>
              </tr>
          <% end %>

          </tbody>
        </table>



<div >

  <%= will_paginate @contents, previous_label:'上一页', next_label: '下一页' %>
</div>
        <%= link_to '创建文章',new_content_path,class:"btn-small btn-color btn-pad pull-right",'data-no-turbolink' => true %>
      </div>


    </div>
  </div>
</div>
<br>
<br>
<%= render 'footer' %>

app/views/contents/new.html.erb
<%= render 'admintop' %>





<div id="main">
  <div class="breadcrumb-wrapper">
    <div class="container">




      <div class="row">
        <div class="col-lg-12 col-md-12">
          <h3 class="title">Form Elements</h3>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 ">
              <%= form_for(@content,:html => {:multipart => true}) do |f| %>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">
                      栏目:
                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.hidden_field :cla_id,class:"form-control"  %>
                    <select class="form-control">
                      <% @clas.each do |cla| %>
                          <option value=<%= cla.id %> ><%= cla.title %></option>
                      <% end %>
                    </select>
                  </div>
                  <br>
                  <br>



                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">
                      标题
                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_field :title ,class:"form-control" %>
                  </div>
                  <br>
                  <br>






                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">
                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <div class="pull-right">
                      <%= f.submit '确定',class:'btn-small btn-color btn-pad' %>

                    </div>
                  </div>




                  </div>
                  </div>
                  </div>
                  </div>
                  <!-- End 5th Row-->






              <% end %>

              </div>
  </div>
</div>

app/views/contents/show.html.erb
<%= render 'admintop' %>


<div class="container content">
  <%= form_for(@content,:html => {:multipart => true}) do |f| %>
      <%= f.kindeditor :content, :simple_mode => true,:owner_id => @content.id , :allowFileManager => false %>

      <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
        <div class="pull-right">
          <%= f.submit '确定',class:'btn-small btn-color btn-pad' %>
        </div>

      </div>
  <% end %>

</div>
<%= render 'footer' %>