config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :admins
  root 'tests#index'
  resources :configs
  resources :sliders
  resources :clas
  resources :contents
  resources :wenhuas
  resources :products
  resources :contacts
  resources :news
  resources :messages
  resources :logins
  resources :sitemaps
  resources :mains

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/cla.rb
class Cla < ActiveRecord::Base
  has_many :contents
end

app/models/config.rb
class Config < ActiveRecord::Base
  has_attached_file :logo, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :logo
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :cla
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
  has_many_kindeditor_assets :attachments, :dependent => :destroy
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :cla
  has_many :contents
end

app/models/main.rb
class Main < ActiveRecord::Base
  has_attached_file :mainimage, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :mainimage
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/clas_controller.rb
class ClasController < ApplicationController

  before_action :set_cla, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @clas = Cla.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @cla = Cla.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @cla = Cla.new(cla_params)

    respond_to do |format|
      if @cla.save
        format.html { redirect_to clas_path, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @cla.update(cla_params)
        format.html { redirect_to clas_path, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @cla.destroy
    respond_to do |format|
      format.html { redirect_to clas_path, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cla
    @cla = Cla.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cla_params
    params.require(:cla).permit(:title, :keyword)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/wenhuas_helper.rb
module WenhuasHelper
end

app/views/clas/_form.html.erb
<%= render 'admintop' %>
<div id="main">
  <div class="breadcrumb-wrapper">
    <div class="container">




      <div class="row">
        <div class="col-lg-12 col-md-12">
          <h3 class="title">创建栏目</h3>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 ">
              <%= form_for(@cla,:html => {:multipart => true}) do |f| %>


                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">
                      标题
                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_field :title ,class:"form-control" %>
                  </div>


                  <br>
                  <br>

                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">
                      关键字:
                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <%= f.text_field :keyword,class:"form-control"  %>
                  </div>







                  <br>
                  <br>

                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-4">
                    <p class="pull-right">
                    </p>
                  </div>
                  <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                    <div class="pull-right">
                      <%= f.submit '确定',class:'btn-small btn-color btn-pad' %>

                    </div>
                  </div>




                  </div>
                  </div>
                  </div>
                  </div>
                  <!-- End 5th Row-->






              <% end %>

              </div>
  </div>
</div>
<%= render 'footer' %>

app/views/clas/edit.html.erb
<%= render 'form' %>

app/views/clas/index.html.erb
<%= render 'admintop' %>
<div id="main">
  <div class="breadcrumb-wrapper">
    <div class="container">

      <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 row">
        <h3 class="title">栏目</h3>
        <table class="table table-striped table-bordered">
          <thead>
          <tr>
            <th>标题</th>
            <th>关键字</th>
            <th>操作</th>
          </tr>
          </thead>
          <tbody>
          <% @clas.each do |cla| %>
              <tr>
                <td><%= cla.title %></td>
                <td><%= cla.keyword %></td>

                <td><%= link_to '',edit_cla_path(cla),class:"icon-pencil" %>&nbsp;<%= link_to '', cla, method: :delete, data: { confirm: 'Are you sure?' },class:"icon-trash" %></td>
              </tr>
          <% end %>

          </tbody>
        </table>

        <a class="btn-small btn-color btn-pad pull-right" href=<%= new_cla_path %>>创建栏目</a>
      </div>


    </div>
  </div>
</div>
<%= render 'footer' %>

app/views/clas/new.html.erb
<%= render 'form' %>