config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :admins
  root 'tests#index'
  resources :configs
  resources :sliders
  resources :clas
  resources :contents
  resources :wenhuas
  resources :products
  resources :contacts
  resources :news
  resources :messages
  resources :logins
  resources :sitemaps
  resources :mains

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/cla.rb
class Cla < ActiveRecord::Base
  has_many :contents
end

app/models/config.rb
class Config < ActiveRecord::Base
  has_attached_file :logo, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :logo
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :cla
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
  has_many_kindeditor_assets :attachments, :dependent => :destroy
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :cla
  has_many :contents
end

app/models/main.rb
class Main < ActiveRecord::Base
  has_attached_file :mainimage, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :mainimage
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def index
    @news = Cla.find_by(keyword:"news").contents
    @products = Cla.find_by(keyword:"product").contents
  end


  def show
    @sitemaps = Content.find(params[:id])
    @products = Content.all


  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/wenhuas_helper.rb
module WenhuasHelper
end

app/views/sitemaps/index.html.erb
<%= render 'top' %>
<!-- Title, Breadcrumb Start-->
<div class="breadcrumb-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
        <h2 class="title">站内导航</h2>
      </div>
      <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
        <div class="breadcrumbs pull-right">
          <ul>
            <li>你在这里:</li>
            <li><a href="#">站内导航</a></li>

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- Main Content start-->
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 sitemap">
        <h3 class="title">导航</h3>
        <ul>
          <li>
            <%= link_to '关于我们','/','data-no-turbolink' => true %>
          </li>
          <li>
              <%= link_to '新闻中心',news_index_path %>
            <ul>
              <% @news.each do |new| %>
                  <li><%= link_to new.title,news_path(new) %></li>
              <% end %>
            </ul>
          </li>
          <li>
            <a href=<%= wenhuas_path %> class="sf-with-ul">
              企业文化</a>
          </li>
          <li>
            <a href=<%= products_path %> class="sf-with-ul">
              产品中心</a>
            <ul>
              <% @products.each do |product| %>
                  <li><%= link_to product.title, product_path(product) %> </li>
              <%end%>
            </ul>
          </li>
          <li>
            <a href=<%= contacts_path %> class="sf-with-ul">
              联系我们 </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Main Content end-->
<%= render 'footer' %>