config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :admins
  root 'tests#index'
  resources :configs
  resources :sliders
  resources :clas
  resources :contents
  resources :wenhuas
  resources :products
  resources :contacts
  resources :news
  resources :messages
  resources :logins
  resources :sitemaps
  resources :mains

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/cla.rb
class Cla < ActiveRecord::Base
  has_many :contents
end

app/models/config.rb
class Config < ActiveRecord::Base
  has_attached_file :logo, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :logo
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :cla
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
  has_many_kindeditor_assets :attachments, :dependent => :destroy
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :cla
  has_many :contents
end

app/models/main.rb
class Main < ActiveRecord::Base
  has_attached_file :mainimage, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :mainimage
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :image, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :image
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

  before_action :set_main, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @mains = Main.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @main = Main.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to mains_path, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to mains_path, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_path, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_main
    @main = Main.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def main_params
    params.require(:main).permit(:title, :summary, :mainimage)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/wenhuas_helper.rb
module WenhuasHelper
end

app/views/mains/_form.html.erb
<%= form_for(@main) do |f| %>

    <div class="field">
      <%= f.label :标题 %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :内容 %><br>
      <%= f.number_field :summary %>
    </div>
    <div class="field">
      <%= f.label :图片 %><br>
      <%= f.number_field :mainimage %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/mains/index.html.erb
<%= render 'admintop' %>

<div id="titlebar" class="titlebar-hautq cover">
  <div class="container relative" >
    <div id="titlebar-text" >
      <h4 id="titlebar-title">网站建设</h4>
    </div>
  </div>
</div>

<br>

<div class="container">

  <table class="table table-striped table-bordered">
    <tr>
      <td>标题</td>
      <td>操作</td>
    </tr>
    <% @mains.each do |f| %>
        <tr>
          <td><%= f.title %></td>
          <td><%= link_to '编辑',edit_main_path(f) %>&nbsp;&nbsp;<%= link_to '删除', f, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>

  </table>

  <%= link_to '新建',new_main_path,class:'btn btn-primary pull-right' %>
</div>

app/views/mains/new.html.erb
<%= render 'admintop'  %>
<%= render 'form' %>